# -*- coding: utf-8 -*-
"""Projeto advinhação.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W7j2jP3GLjnSxB9jfXzcpjsv6F4TwR6D
"""

times =('flamengo','corinthians','barcelona')

excluir=(input("Qual time voce deseja excluir?"))

times = list(times)
times.remove(excluir)
times = tuple(times)
print(times)

import random

numero = random.randint(1, 100)
tentativas =0

print("Ben-vindo ao jogo de advinhação!")
print("Eu escolhi um numero entre 1 e 100 e voce tem 10 tentativas para advinhar")

while tentativas< 10:
    palpite = int(input("Digite o seu palpite:"))
    tentativas+= 1

    if palpite == numero:
      print(f"Parabens!,Voceacertou o numero em {tentativas} tentativas.")
      break
    elif palpite < numero:
      print("O numero e maior, tente novamente")
    else:
      print("O numero e menor, tente novamente.")
else:
    print(f"Voce perdeu!, O numero era{numero}")